export const ERROR_CODES = {
  MISSING_NAME: 'MISSING_NAME',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_IN_WORKSPACE: 'USER_ALREADY_IN_WORKSPACE',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED'
};